packages:
  - apps/*
  - libs/*

catalog:
  '@material/material-color-utilities': ^0.4.0
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': 4.2.4
  vite: 8.0.10
  '@types/node': ^25.6.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  lit: 3.3.2
  next: 16.2.4
  react: 19.2.5
  react-dom: 19.2.5
  tailwindcss: 4.2.4
  typescript: 6.0.3
