import './global.css';

import LiffProvider from './LiffProvider';

export const metadata = {
  title: 'Welcome to personal-liff',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LiffProvider liffId={process.env.LIFF_ID!}>{children}</LiffProvider>
      </body>
    </html>
  );
}
