// apps/loop-observatory/src/lib/enroll/derive.ts
import { type PlistValue, toPlist } from './plist.js';
import {
  type DerivedFile,
  type HostDeclaration,
  type HostFacts,
  UnknownFact,
} from './types.js';

const RALPH_LABEL = 'tools.rainforest.loop-ralph';

function loopHome(d: HostDeclaration): string {
  return `${d.home}/.claude/loop`;
}

function quotaFile(d: HostDeclaration, f: HostFacts): string | null {
  // ralph.sh:314 defaults to $HOME/.local/share/loop-usage-runtime/..., which is
  // the layout of a host that keeps a runtime copy because launchd there cannot
  // read iCloud. A host reading the vault directly needs an explicit path, and
  // that is a property of where its quota lives, not of its name.
  if (!f.vaultPath) return null;
  return `${f.vaultPath}/_system/usage/quota.${d.host}.json`;
}

export function deriveRalphPlist(
  d: HostDeclaration,
  f: HostFacts,
): DerivedFile {
  if (f.tccICloud === 'unknown') throw new UnknownFact('tccICloud');

  const denied = f.tccICloud === 'denied';

  // Only checked on the branch that uses it: the denied branch's PATH is a fixed
  // system list, so an absent Homebrew is not a missing fact there.
  if (!denied && !f.brewPrefix) throw new UnknownFact('brewPrefix');

  // On a host whose launchd cannot read the vault, the loop's environment moves
  // into run-ralph-gui.applescript, which re-enters the logged-in GUI session
  // where the grant exists. Only PATH stays here, for osascript itself. The
  // script ships with the engine role, so this branch needs no extra install.
  const env: Record<string, string> = denied
    ? { PATH: '/usr/bin:/bin:/usr/sbin:/sbin' }
    : {
        PATH: `${d.home}/.local/bin:${f.brewPrefix}/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`,
      };

  const body: Record<string, PlistValue> = {
    Label: RALPH_LABEL,
    ProgramArguments: denied
      ? ['/usr/bin/osascript', `${loopHome(d)}/run-ralph-gui.applescript`]
      : [`${loopHome(d)}/ralph.sh`],
    EnvironmentVariables: env,
    RunAtLoad: true,
    StartInterval: d.intervalSeconds,
    ThrottleInterval: 60,
    StandardOutPath: `${loopHome(d)}/ralph.log`,
    StandardErrorPath: `${loopHome(d)}/ralph.err.log`,
  };

  if (!denied) {
    env.LOOP_MACHINE = d.host;
    if (f.executors.length > 0) env.LOOP_EXECUTORS = f.executors.join(',');
    const quota = quotaFile(d, f);
    if (quota) env.LOOP_QUOTA_FILE = quota;
    if (f.vaultPath)
      env.LOOP_AGENT_CONFIG = `${f.vaultPath}/_system/usage/loop-agents.json`;
  }

  return {
    path: `Library/LaunchAgents/${RALPH_LABEL}.plist`,
    contents: toPlist(body),
  };
}

/**
 * The OTLP intake this executor's own telemetry lands in.
 *
 * `ralph.sh:78` defaults OTLP_ENDPOINT to http://localhost:4318 and injects the
 * exporter env into every `claude -p` it launches. Nothing checks that anything
 * is listening, and the OTel SDK does not complain when nothing is — so a
 * machine can be a healthy executor and throw away everything it measures.
 * Measured 2026-08-26: that was the Air's entire history.
 *
 * Returns null for a host without the role. The mini is the exception that
 * explains the shape: its sink is the homelab's containerised Alloy, already
 * receiving on 4317/4318.
 *
 * Written as a FRAGMENT beside the host's hand-maintained config, never as
 * that config itself. The live host's `com.homelab.dev-alloy` plist points
 * Alloy at the `.config/dev-telemetry/alloy` directory rather than a single
 * file — `alloy run --help`: "If path is a directory, all `*.alloy` files in
 * that directory will be combined into a single unit" — because the existing
 * `config.alloy` there already defines `prometheus.scrape "host"`,
 * `prometheus.remote_write "rpi"`, `local.file_match "dev_events"`,
 * `loki.process "dev_events"`, and `loki.write "rpi"`. This fragment's
 * `otelcol.exporter.prometheus` and `otelcol.exporter.loki` blocks reference
 * `prometheus.remote_write.rpi` and `loki.write.rpi` by name and depend on
 * that sibling file defining them; it does not define its own remote-write
 * destination, because the homelab owns the destinations and the host scrape
 * and dev-events tailing, and this fragment is not the place to redefine or
 * remove them. Writing this to `config.alloy` itself would delete those
 * definitions out from under Alloy, which would then fail to load at all.
 */
export function deriveAlloyConfig(
  d: HostDeclaration,
  f: HostFacts,
): DerivedFile | null {
  if (!d.roles.includes('telemetry-sink')) return null;
  if (f.tccICloud === 'unknown') throw new UnknownFact('tccICloud');

  const contents = `// Generated by Loop Observatory enrollment. Do not edit by hand;
// re-enroll instead. Inputs: this host's declaration and its probed facts.
//
// Bound to ${d.otlpBind}, which is declared rather than probed: whether this
// machine opens a port to the network must not be a side effect of what a probe
// happened to find.

otelcol.receiver.otlp "agents" {
  http {
    endpoint = "${d.otlpBind}:4318"
  }

  output {
    metrics = [otelcol.processor.batch.agents.input]
    logs    = [otelcol.processor.batch.agents.input]
  }
}

otelcol.processor.batch "agents" {
  timeout = "2s"

  output {
    metrics = [otelcol.exporter.prometheus.agents.input]
    logs    = [otelcol.exporter.loki.agents.input]
  }
}

otelcol.exporter.prometheus "agents" {
  forward_to = [prometheus.remote_write.rpi.receiver]
}

otelcol.exporter.loki "agents" {
  forward_to = [loki.write.rpi.receiver]
}
`;
  return { path: '.config/dev-telemetry/alloy/loop-otlp.alloy', contents };
}

/** Every file this host needs. Pure: the only entry point callers should use. */
export function derive(d: HostDeclaration, f: HostFacts): DerivedFile[] {
  const files: DerivedFile[] = [];
  if (d.roles.includes('ralph')) files.push(deriveRalphPlist(d, f));
  const alloy = deriveAlloyConfig(d, f);
  if (alloy) files.push(alloy);
  return files;
}
