/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiBrowseRouteImport } from './routes/api/browse'
import { Route as ApiSessionsIndexRouteImport } from './routes/api/sessions/index'
import { Route as ApiBrowseCreateRouteImport } from './routes/api/browse/create'
import { Route as ApiSessionsSessionIdStreamRouteImport } from './routes/api/sessions/$sessionId/stream'
import { Route as ApiSessionsSessionIdChatRouteImport } from './routes/api/sessions/$sessionId/chat'
import { Route as ApiSessionsSessionIdApproveRouteImport } from './routes/api/sessions/$sessionId/approve'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowseRoute = ApiBrowseRouteImport.update({
  id: '/api/browse',
  path: '/api/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIndexRoute = ApiSessionsIndexRouteImport.update({
  id: '/api/sessions/',
  path: '/api/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowseCreateRoute = ApiBrowseCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiBrowseRoute,
} as any)
const ApiSessionsSessionIdStreamRoute =
  ApiSessionsSessionIdStreamRouteImport.update({
    id: '/api/sessions/$sessionId/stream',
    path: '/api/sessions/$sessionId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsSessionIdChatRoute =
  ApiSessionsSessionIdChatRouteImport.update({
    id: '/api/sessions/$sessionId/chat',
    path: '/api/sessions/$sessionId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsSessionIdApproveRoute =
  ApiSessionsSessionIdApproveRouteImport.update({
    id: '/api/sessions/$sessionId/approve',
    path: '/api/sessions/$sessionId/approve',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/browse': typeof ApiBrowseRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/api/browse/create': typeof ApiBrowseCreateRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/sessions/$sessionId/approve': typeof ApiSessionsSessionIdApproveRoute
  '/api/sessions/$sessionId/chat': typeof ApiSessionsSessionIdChatRoute
  '/api/sessions/$sessionId/stream': typeof ApiSessionsSessionIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/browse': typeof ApiBrowseRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/api/browse/create': typeof ApiBrowseCreateRoute
  '/api/sessions': typeof ApiSessionsIndexRoute
  '/api/sessions/$sessionId/approve': typeof ApiSessionsSessionIdApproveRoute
  '/api/sessions/$sessionId/chat': typeof ApiSessionsSessionIdChatRoute
  '/api/sessions/$sessionId/stream': typeof ApiSessionsSessionIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/browse': typeof ApiBrowseRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/api/browse/create': typeof ApiBrowseCreateRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/sessions/$sessionId/approve': typeof ApiSessionsSessionIdApproveRoute
  '/api/sessions/$sessionId/chat': typeof ApiSessionsSessionIdChatRoute
  '/api/sessions/$sessionId/stream': typeof ApiSessionsSessionIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/browse'
    | '/api/projects'
    | '/sessions/$sessionId'
    | '/api/browse/create'
    | '/api/sessions/'
    | '/api/sessions/$sessionId/approve'
    | '/api/sessions/$sessionId/chat'
    | '/api/sessions/$sessionId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/browse'
    | '/api/projects'
    | '/sessions/$sessionId'
    | '/api/browse/create'
    | '/api/sessions'
    | '/api/sessions/$sessionId/approve'
    | '/api/sessions/$sessionId/chat'
    | '/api/sessions/$sessionId/stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/browse'
    | '/api/projects'
    | '/sessions/$sessionId'
    | '/api/browse/create'
    | '/api/sessions/'
    | '/api/sessions/$sessionId/approve'
    | '/api/sessions/$sessionId/chat'
    | '/api/sessions/$sessionId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiBrowseRoute: typeof ApiBrowseRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  ApiSessionsIndexRoute: typeof ApiSessionsIndexRoute
  ApiSessionsSessionIdApproveRoute: typeof ApiSessionsSessionIdApproveRoute
  ApiSessionsSessionIdChatRoute: typeof ApiSessionsSessionIdChatRoute
  ApiSessionsSessionIdStreamRoute: typeof ApiSessionsSessionIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browse': {
      id: '/api/browse'
      path: '/api/browse'
      fullPath: '/api/browse'
      preLoaderRoute: typeof ApiBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/': {
      id: '/api/sessions/'
      path: '/api/sessions'
      fullPath: '/api/sessions/'
      preLoaderRoute: typeof ApiSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browse/create': {
      id: '/api/browse/create'
      path: '/create'
      fullPath: '/api/browse/create'
      preLoaderRoute: typeof ApiBrowseCreateRouteImport
      parentRoute: typeof ApiBrowseRoute
    }
    '/api/sessions/$sessionId/stream': {
      id: '/api/sessions/$sessionId/stream'
      path: '/api/sessions/$sessionId/stream'
      fullPath: '/api/sessions/$sessionId/stream'
      preLoaderRoute: typeof ApiSessionsSessionIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/chat': {
      id: '/api/sessions/$sessionId/chat'
      path: '/api/sessions/$sessionId/chat'
      fullPath: '/api/sessions/$sessionId/chat'
      preLoaderRoute: typeof ApiSessionsSessionIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/approve': {
      id: '/api/sessions/$sessionId/approve'
      path: '/api/sessions/$sessionId/approve'
      fullPath: '/api/sessions/$sessionId/approve'
      preLoaderRoute: typeof ApiSessionsSessionIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiBrowseRouteChildren {
  ApiBrowseCreateRoute: typeof ApiBrowseCreateRoute
}

const ApiBrowseRouteChildren: ApiBrowseRouteChildren = {
  ApiBrowseCreateRoute: ApiBrowseCreateRoute,
}

const ApiBrowseRouteWithChildren = ApiBrowseRoute._addFileChildren(
  ApiBrowseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiBrowseRoute: ApiBrowseRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  ApiSessionsIndexRoute: ApiSessionsIndexRoute,
  ApiSessionsSessionIdApproveRoute: ApiSessionsSessionIdApproveRoute,
  ApiSessionsSessionIdChatRoute: ApiSessionsSessionIdChatRoute,
  ApiSessionsSessionIdStreamRoute: ApiSessionsSessionIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
