import { fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { OrderBook } from './OrderBook';

describe('<OrderBook>', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('mounts and renders the shuffle control and mid price', () => {
    render(<OrderBook />);
    expect(
      screen.getByRole('button', { name: /shuffle the book/i }),
    ).toBeDefined();
    expect(screen.getByText('1.2431')).toBeDefined();
  });

  it('closes the offer preview when "shuffle the book" replaces the selected level — the ghost-level invariant', () => {
    // Deterministic, ever-changing jitter so the book generated by the
    // shuffle click never coincidentally matches the book generated on
    // mount (which would make this test flaky either way).
    let counter = 0;
    vi.spyOn(Math, 'random').mockImplementation(() => {
      counter += 1;
      return (counter % 97) / 97;
    });

    render(<OrderBook />);
    const levelButtons = screen.getAllByRole('button', {
      name: /^(Ask|Bid) /,
    });
    fireEvent.click(levelButtons[0]);
    expect(screen.getByText(/take (ask|bid) ·/i)).toBeDefined();

    fireEvent.click(screen.getByRole('button', { name: /shuffle the book/i }));

    expect(screen.queryByText(/take (ask|bid) ·/i)).toBeNull();
    expect(screen.getByText(/level replaced/i)).toBeDefined();
  });
});
