import plugin from 'tailwindcss/plugin';

interface IOptions {
  sourceColor?: string;
}

// `var()` is substituted where the property is declared and the resolved value is what
// inherits, so these are spread into every scheme block: declared once on `:root`, a nested
// `[data-scheme]` subtree would keep the root's colours.
const sidebarAliases: Record<string, string> = {
  '--sidebar-foreground': 'var(--foreground)',
  '--sidebar-primary': 'var(--primary)',
  '--sidebar-primary-foreground': 'var(--primary-foreground)',
  '--sidebar-accent': 'var(--accent)',
  '--sidebar-accent-foreground': 'var(--accent-foreground)',
  '--sidebar-border': 'var(--border)',
  '--sidebar-ring': 'var(--ring)',
};

const lightVars = (seed: string): Record<string, string> => ({
  '--seed': `var(--shadcn-seed-override, ${seed})`,
  '--background': 'oklch(from var(--seed) 0.98 0.012 h)',
  '--foreground': 'oklch(from var(--seed) 0.19 0.02 h)',
  '--card': 'oklch(from var(--seed) 0.995 0.008 h)',
  '--card-foreground': 'oklch(from var(--seed) 0.19 0.02 h)',
  '--popover': 'oklch(from var(--seed) 0.995 0.008 h)',
  '--popover-foreground': 'oklch(from var(--seed) 0.19 0.02 h)',
  '--primary': 'oklch(from var(--seed) 0.55 0.12 h)',
  '--primary-foreground': 'oklch(from var(--seed) 0.98 0.012 h)',
  '--secondary': 'oklch(from var(--seed) 0.94 0.02 h)',
  '--secondary-foreground': 'oklch(from var(--seed) 0.25 0.03 h)',
  '--muted': 'oklch(from var(--seed) 0.94 0.015 h)',
  '--muted-foreground': 'oklch(from var(--seed) 0.48 0.02 h)',
  '--accent': 'oklch(from var(--seed) 0.9 0.035 h)',
  '--accent-foreground': 'oklch(from var(--seed) 0.25 0.03 h)',
  '--destructive': 'oklch(0.5 0.19 27.325)',
  '--destructive-foreground': 'oklch(0.98 0.01 27.325)',
  '--border': 'oklch(from var(--seed) 0.88 0.015 h)',
  '--input': 'oklch(from var(--seed) 0.88 0.015 h)',
  '--ring': 'oklch(from var(--seed) 0.55 0.12 h)',
  '--success': 'oklch(0.48 0.12 150)',
  '--success-foreground': 'oklch(0.98 0.01 150)',
  '--warning': 'oklch(0.5 0.11 70)',
  '--warning-foreground': 'oklch(0.98 0.01 70)',
  '--info': 'oklch(0.49 0.12 250)',
  '--info-foreground': 'oklch(0.98 0.01 250)',
  '--chart-1': 'oklch(from var(--seed) 0.55 0.12 h)',
  '--chart-2': 'oklch(from var(--seed) 0.65 0.11 calc(h + 60))',
  '--chart-3': 'oklch(from var(--seed) 0.5 0.1 calc(h + 150))',
  '--chart-4': 'oklch(from var(--seed) 0.72 0.12 calc(h + 210))',
  '--chart-5': 'oklch(from var(--seed) 0.6 0.13 calc(h + 290))',
  '--sidebar': 'oklch(from var(--seed) 0.965 0.014 h)',
  ...sidebarAliases,
});

const darkVars: Record<string, string> = {
  '--background': 'oklch(from var(--seed) 0.17 0.02 h)',
  '--foreground': 'oklch(from var(--seed) 0.93 0.015 h)',
  '--card': 'oklch(from var(--seed) 0.21 0.02 h)',
  '--card-foreground': 'oklch(from var(--seed) 0.93 0.015 h)',
  '--popover': 'oklch(from var(--seed) 0.21 0.02 h)',
  '--popover-foreground': 'oklch(from var(--seed) 0.93 0.015 h)',
  '--primary': 'oklch(from var(--seed) 0.75 0.11 h)',
  '--primary-foreground': 'oklch(from var(--seed) 0.17 0.02 h)',
  '--secondary': 'oklch(from var(--seed) 0.27 0.02 h)',
  '--secondary-foreground': 'oklch(from var(--seed) 0.93 0.015 h)',
  '--muted': 'oklch(from var(--seed) 0.27 0.02 h)',
  '--muted-foreground': 'oklch(from var(--seed) 0.65 0.02 h)',
  '--accent': 'oklch(from var(--seed) 0.32 0.035 h)',
  '--accent-foreground': 'oklch(from var(--seed) 0.93 0.015 h)',
  '--destructive': 'oklch(0.7 0.17 25)',
  '--destructive-foreground': 'oklch(0.17 0.02 25)',
  '--border': 'oklch(from var(--seed) 0.32 0.02 h)',
  '--input': 'oklch(from var(--seed) 0.32 0.02 h)',
  '--ring': 'oklch(from var(--seed) 0.75 0.11 h)',
  '--success': 'oklch(0.76 0.14 150)',
  '--success-foreground': 'oklch(0.17 0.02 150)',
  '--warning': 'oklch(0.8 0.13 80)',
  '--warning-foreground': 'oklch(0.17 0.02 80)',
  '--info': 'oklch(0.75 0.11 250)',
  '--info-foreground': 'oklch(0.17 0.02 250)',
  '--chart-1': 'oklch(from var(--seed) 0.75 0.11 h)',
  '--chart-2': 'oklch(from var(--seed) 0.78 0.11 calc(h + 60))',
  '--chart-3': 'oklch(from var(--seed) 0.68 0.1 calc(h + 150))',
  '--chart-4': 'oklch(from var(--seed) 0.82 0.11 calc(h + 210))',
  '--chart-5': 'oklch(from var(--seed) 0.72 0.12 calc(h + 290))',
  '--sidebar': 'oklch(from var(--seed) 0.19 0.02 h)',
  ...sidebarAliases,
};

// Static fallback for engines without relative-color-syntax support (pre-Safari 26),
// pre-resolved from the default teal seed (#66b2b2).
const fallbackLight: Record<string, string> = {
  '--seed': '#66b2b2',
  '--background': '#f7fafa',
  '--foreground': '#1c2b2b',
  '--card': '#fdffff',
  '--card-foreground': '#1c2b2b',
  '--popover': '#fdffff',
  '--popover-foreground': '#1c2b2b',
  '--primary': '#3e7d7d',
  '--primary-foreground': '#f7fafa',
  '--secondary': '#e2f0ef',
  '--secondary-foreground': '#23403f',
  '--muted': '#e4f1f0',
  '--muted-foreground': '#5c7877',
  '--accent': '#cfe8e6',
  '--accent-foreground': '#23403f',
  '--destructive': '#b71a1b',
  '--destructive-foreground': '#fdf2f1',
  '--border': '#d2e3e2',
  '--input': '#d2e3e2',
  '--ring': '#3e7d7d',
  '--success': '#197037',
  '--success-foreground': '#f4fbf5',
  '--warning': '#8a5600',
  '--warning-foreground': '#fdf8ef',
  '--info': '#1e63a1',
  '--info-foreground': '#f3f8fd',
  '--chart-1': '#3e7d7d',
  '--chart-2': '#6091d1',
  '--chart-3': '#8b4a70',
  '--chart-4': '#e28b62',
  '--chart-5': '#6e8d2b',
  '--sidebar': '#e9f7f6',
};

const fallbackDark: Record<string, string> = {
  '--background': '#182626',
  '--foreground': '#e8f2f1',
  '--card': '#1e3030',
  '--card-foreground': '#e8f2f1',
  '--popover': '#1e3030',
  '--popover-foreground': '#e8f2f1',
  '--primary': '#8fc9c8',
  '--primary-foreground': '#182626',
  '--secondary': '#2c4443',
  '--secondary-foreground': '#e8f2f1',
  '--muted': '#2c4443',
  '--muted-foreground': '#a7bdbc',
  '--accent': '#35504f',
  '--accent-foreground': '#e8f2f1',
  '--destructive': '#f66d67',
  '--destructive-foreground': '#170c0b',
  '--border': '#35504f',
  '--input': '#35504f',
  '--ring': '#8fc9c8',
  '--success': '#68ca80',
  '--success-foreground': '#0b1a10',
  '--warning': '#e9b452',
  '--warning-foreground': '#1c1505',
  '--info': '#76b3f1',
  '--info-foreground': '#0a1624',
  '--chart-1': '#8fc9c8',
  '--chart-2': '#88bafd',
  '--chart-3': '#c57fa6',
  '--chart-4': '#ffad87',
  '--chart-5': '#92b25b',
  '--sidebar': '#1b2b2b',
};

export default plugin.withOptions(
  ({ sourceColor = '#66b2b2' }: IOptions = {}) => {
    const light = lightVars(sourceColor);
    return ({ addBase }) => {
      addBase({
        ':root': light,
        "[data-scheme='light']": light,
        // Gate the OS-preference rule on `:not([data-scheme])` so an explicit
        // `[data-scheme='light'|'dark']` always wins. Without it the media
        // query and `[data-scheme='light']` tie on specificity and the later
        // media rule overrides — making "force light" silently fail on an
        // OS-dark device (a manual light/dark toggle can't work otherwise).
        '@media (prefers-color-scheme: dark)': {
          ':root:not([data-scheme])': darkVars,
        },
        "[data-scheme='dark']": darkVars,
        '@supports not (color: oklch(from red l c h))': {
          ':root': fallbackLight,
          "[data-scheme='light']": fallbackLight,
          '@media (prefers-color-scheme: dark)': {
            ':root:not([data-scheme])': fallbackDark,
          },
          "[data-scheme='dark']": fallbackDark,
        },
      });
    };
  },
  () => ({
    theme: {
      extend: {
        colors: {
          background: 'var(--background)',
          foreground: 'var(--foreground)',
          card: 'var(--card)',
          'card-foreground': 'var(--card-foreground)',
          popover: 'var(--popover)',
          'popover-foreground': 'var(--popover-foreground)',
          primary: 'var(--primary)',
          'primary-foreground': 'var(--primary-foreground)',
          secondary: 'var(--secondary)',
          'secondary-foreground': 'var(--secondary-foreground)',
          muted: 'var(--muted)',
          'muted-foreground': 'var(--muted-foreground)',
          accent: 'var(--accent)',
          'accent-foreground': 'var(--accent-foreground)',
          destructive: 'var(--destructive)',
          'destructive-foreground': 'var(--destructive-foreground)',
          border: 'var(--border)',
          input: 'var(--input)',
          ring: 'var(--ring)',
          success: 'var(--success)',
          'success-foreground': 'var(--success-foreground)',
          warning: 'var(--warning)',
          'warning-foreground': 'var(--warning-foreground)',
          info: 'var(--info)',
          'info-foreground': 'var(--info-foreground)',
          'chart-1': 'var(--chart-1)',
          'chart-2': 'var(--chart-2)',
          'chart-3': 'var(--chart-3)',
          'chart-4': 'var(--chart-4)',
          'chart-5': 'var(--chart-5)',
          sidebar: 'var(--sidebar)',
          'sidebar-foreground': 'var(--sidebar-foreground)',
          'sidebar-primary': 'var(--sidebar-primary)',
          'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
          'sidebar-accent': 'var(--sidebar-accent)',
          'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
          'sidebar-border': 'var(--sidebar-border)',
          'sidebar-ring': 'var(--sidebar-ring)',
        },
        borderRadius: {
          sm: 'calc(var(--radius) - 4px)',
          md: 'calc(var(--radius) - 2px)',
          lg: 'var(--radius)',
          xl: 'calc(var(--radius) + 4px)',
        },
      },
    },
  }),
);
